apiVersion: batch/v1
kind: Job
metadata:
  name: loadgen
spec:
  template:
    metadata:
      name: loadgen
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: locust
        image: locustio/locust:1.0.3
        tty: true
        stdin: true
        stdinOnce: true
        command: [ "/bin/sh", "-c" ]
        args: [ "/usr/local/bin/locust $(LOCUST_OPTS) -f $(LOCUSTFILE_PATH) --host $(TARGET_URL)" ]
        env:
        - name: LOCUSTFILE_PATH
          value: /mnt/locustfile.py
        - name: LOCUST_OPTS
          valueFrom:
            configMapKeyRef:
              name: locust-config
              key: locustOpts
        - name: TARGET_URL
          valueFrom:
            configMapKeyRef:
              name: locust-config
              key: targetUrl
        volumeMounts:
        - name: locust-file-vol
          mountPath: /mnt/locustfile.py
          subPath: locustfile.py
      volumes:
      - name: locust-file-vol
        configMap:
          name: locust-file
      restartPolicy: Never
